// <auto-generated />
namespace MVCMusicStore.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class entityconnections1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(entityconnections1));
        
        string IMigrationMetadata.Id
        {
            get { return "201804091720206_entity connections1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
